services:
  dashboard:
    container_name: dashboard
    image: nitheesh2005/dashboard:latest
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - /opt/app/nginx/conf.d:/etc/nginx/conf.d:ro
      # remove nginx.conf override if file doesn't exist
      # - /opt/app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
